package com.example.weibo2.api

import com.example.weibo2.api.Status

class User(
    val id: Long,
    val idstr: String,
    val screen_name: String,
    val name: String,
    val province: Int,
    val city: Int,
    val location: String,
    val description: String,
    val url: String,
    val profile_image_uri: String,
    val profile_url: String,
    val domain: String,
    val weihao: String,
    val gender: String,
    val followers_count: Int,
    val friends_count: Int,
    val statuses_count: Int,
    val favourites_count: Int,
    val created_at: String,
    val following: Boolean,
    val allow_all_act_msg: Boolean,
    val geo_enabled: Boolean,
    val verified: Boolean,
    val verified_type: Int,
    val remark: String,
    val status: Status,
    val allow_all_comment: Boolean,
    val avatar_large: String,
    val avatar_hd: String,
    val verified_reason: String,
    val follow_me: Boolean,
    val online_status: Int,
    val bi_followers_count: Int,
    val lang: String
)